version: '3.9'

services:
  backend:
    build:
      context: ./backend/
      dockerfile: Dockerfile
    volumes:
      - $PWD/backend/conf/:/app/conf/
      - $PWD/backend/data/:/app/data/
    ports:
      - "9999:9999"

  frontend:
    build:
      context: ./frontend/
      dockerfile: Dockerfile
    ports:
      - "3000:3000"